apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: dataopsbox
  labels:
    app: loki-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-server
  template:
    metadata:
      labels:
        app: loki-server
    spec:
      containers:
        - name: loki
          image: loki:latest
          imagePullPolicy: Never
          args:
            - "--config.file=/etc/loki/config.yaml"
          ports:
            - containerPort: 3100