apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  namespace: dataopsbox
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector: 
    app: alertmanager
  clusterIP: "10.106.4.84"
  type: LoadBalancer  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 32000