apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: dataopsbox
spec:
  clusterIP: "10.106.1.84"
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer