# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: kafka-kraft-svc
  namespace: dataopsbox
spec:
  clusterIP: "10.106.7.84"
  type: LoadBalancer
  selector:
    app: kafka-kraft
  ports:
    - name: "external"
      port: 9093
      targetPort: 9093
    - name: "internal"
      port: 9092
      targetPort: 9092